// react/personal-finance-manager/src/nav/Navbar.tsx
import "./Navbar.css";
import { NavLink } from "react-router-dom";

const routes = [
  { path: "/", label: "Dashboard" },
  { path: "/expenses", label: "Expenses" },
];

const Navbar = () => {
  return (
    <nav className="nav">
      {routes.map((route) => (
        <NavLink key={route.path} to={route.path}>
          {route.label}
        </NavLink>
      ))}
    </nav>
  );
};

export default Navbar;

// angular/personal-finance-manager/src/app/navbar/navbar.component.ts
import { Component } from "@angular/core";
import { CommonModule } from "@angular/common";
import { RouterLink, RouterLinkActive } from "@angular/router";

@Component({
  selector: "app-navbar",
  standalone: true,
  imports: [CommonModule, RouterLink, RouterLinkActive],
  templateUrl: "./navbar.component.html",
  styleUrls: ["./navbar.component.css"],
})
export class NavbarComponent {
  routes = [
    { path: '/', label: 'Dashboard', exact: true },
    { path: '/expenses', label: 'Expenses', exact: false },
  ];
}
<nav class="navbar">
  <a
    *ngFor="let route of routes"
    [routerLink]="route.path"
    routerLinkActive="active"
    [routerLinkActiveOptions]="{ exact: route.exact }"
  >
    {{ route.label }}
  </a>
</nav>
